#pragma once
#include "CoreMinimal.h"
#include "Animation/AnimNotifies/AnimNotify.h"
#include "EFortSoundIndicatorTypes.h"
#include "FortAnimNotify_GenericSoundIndicator.generated.h"

class USoundBase;

UCLASS(Blueprintable, CollapseCategories, EditInlineNew, MinimalAPI)
class UFortAnimNotify_GenericSoundIndicator : public UAnimNotify {
    GENERATED_BODY()
public:
protected:
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TSoftObjectPtr<USoundBase> BaseSound;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    float MaxAudibleDistance;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    EFortSoundIndicatorTypes IndicatorType;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    bool bIgnoreForLocalPlayer;
    
public:
    UFortAnimNotify_GenericSoundIndicator();
};

