#pragma once
#include "CoreMinimal.h"
#include "FortClientPilot_FrontendBase.h"
#include "FortClientPilot_FrontendCampaign.generated.h"

UCLASS(Blueprintable)
class UFortClientPilot_FrontendCampaign : public UFortClientPilot_FrontendBase {
    GENERATED_BODY()
public:
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    bool bShouldPickRandomMap;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    int32 iSelectedTheater;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    int32 iSelectedTile;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TArray<int32> SelectedTileList;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    float RandomZoneDifficultyMinimum;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    float RandomZoneDifficultyMaximum;
    
    UFortClientPilot_FrontendCampaign();
};

