#pragma once
#include "CoreMinimal.h"
#include "UObject/NoExportTypes.h"
#include "Layout/Margin.h"
#include "FortItemCard_DurabilityMeter_Configuration.h"
#include "FortItemCard_PowerRatingBlock_ItemInstance_Configuration.h"
#include "FortItemCard_StackCountBlock_Configuration.h"
#include "FortItemCard_TierMeter_Configuration.h"
#include "FortItemCard_S_ItemInstance_Configuration.generated.h"

USTRUCT(BlueprintType)
struct FFortItemCard_S_ItemInstance_Configuration {
    GENERATED_BODY()
public:
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FMargin BackgroundPadding;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FMargin PowerRatingBlockPadding;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FFortItemCard_PowerRatingBlock_ItemInstance_Configuration PowerRatingBlock;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FVector2D BookmarkImageSize;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FFortItemCard_StackCountBlock_Configuration StackCountBlock;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FMargin TraitBoxPadding;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FVector2D FirstTraitSize;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FMargin TierMeterPadding;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FFortItemCard_TierMeter_Configuration TierMeter;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FFortItemCard_DurabilityMeter_Configuration DurabilityMeter;
    
    FORTNITEUI_API FFortItemCard_S_ItemInstance_Configuration();
};

